In [9]:
import nbimporter

### Simulator Backend

In [3]:
from qiskit import Aer
from qiskit.utils import QuantumInstance, algorithm_globals

seed = 50
algorithm_globals.random_seed = seed

backend = Aer.get_backend('qasm_simulator')

### BFGS Optimizer

In [4]:
from qiskit.algorithms.optimizers import L_BFGS_B

bfgs_optimizer = L_BFGS_B(maxiter=60)

### k input states (computational basis)

In [5]:
from utiles import *

In [6]:
k = 4
n = 16
input_states = get_first_k_eigenvectors_from_n_computational_basis(k, n)
print(input_states)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Ansatz State

In [15]:
import numpy as np
from ansatz_circuit_item2 import get_full_variational_quantum_circuit

In [14]:
init_circuit_params = {
    "thetas": np.random.uniform(low=0, high=2*np.pi, size=8),
    "phis": np.random.uniform(low=0, high=2*np.pi, size=4),
    "D1": 2,
    "D2": 6
}

In [13]:
def get_ansatz_state(circuit_params, input_state):
    circuit_params_with_input_state = {**circuit_params, "input_state": input_state}
    return get_full_variational_quantum_circuit(**circuit_params_with_input_state)

### Expectation Value

In [26]:
def get_expectation_value(hamiltonian, ket_state_vector):
    bra_state_vector = np.matrix(ket_state_vector).getH()
    right_mult = np.matmul(hamiltonian, np.array(ket_state_vector))
    print(np.array(ket_state_vector))
    print(np.array(bra_state_vector))
    print(right_mult)
    return np.matmul(bra_state_vector, right_mult)

hamiltonian = np.identity(16)
print(get_expectation_value(hamiltonian, input_states[0]))

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 16 is different from 1)

### Objective Function